name: PlayerWorldsPro
version: 5.1.9
main: cz._heropwp.playerworldspro.Main
api-version: '1.13'
description: The most advanced Player Worlds plugin with many cool features!
website: https://www.spigotmc.org/members/_heropwp.425110/
author: _HeroPwP
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  PlayerWorldsPro:
    description: Main command of the plugin.
    aliases:
      - pw
      - pwp
      - playerworlds
      - world